export const eurasia = [
  'Afghanistan',
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Brunei',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'East Timor',
  'Estonia',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Oman',
  'Pakistan',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'San Marino',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Turkey',
  'Turkmenistan',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'Uzbekistan',
  'Abkhazia',
  'Artsakh',
  'Kosovo',
  'Northern Cyprus',
  'South Ossetia',
  'Transnistria',
];
export const galleryCountries = [
  'United Kingdom',
  'Poland / Romania',
  'United Arab Emirates',
  'Turkey',
  'Kazakhstan',
  'Azerbaijan',
  'Uzbekistan',
];
export const countries = [
  'United Kingdom',
  'Poland',
  'Romania',
  'United Arab Emirates',
  'Turkey',
  'Kazakhstan',
  'Azerbaijan',
  'Uzbekistan',
];

export const industries = [
  'Transport_Logistics',
  'Energy_Electrical_Equipment',
  'Healthcare_Beauty',
  'Travel_Tourism',
  'Security_Safety',
  'OilGas',
  'Military',
  'Textile',
  'Chemie',
  'Heat_Vent',
  'Hotels,_Restaurants,_Cleaning',
  'Food_Pack,Agriculture',
  'Occupational_Safety_and_Health',
  'Mining_Industry',
  'Building_Interiors',
  'Furniture_Woodwork',
];
